### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by ionutale** [yakuter/gpass#14]
Hi, 
i created an account on gpass.io to see how is made.
i think has some very nice features:

###Types 
you can create types with predefined fields. This allows for multiple type of credentials.
<img width="584" alt="Schermata 2020-04-08 alle 07 00 36" src="https://user-images.githubusercontent.com/2562455/78746805-1f7bfb00-7968-11ea-99af-cef89e5c8eec.png">

###Folders
you can group credentials into folders. 
<img width="741" alt="Schermata 2020-04-08 alle 07 01 41" src="https://user-images.githubusercontent.com/2562455/78746973-85688280-7968-11ea-9cda-37b330ba41d6.png">

###Tags 
very useful

###Adding new fields for same entry
on every credentials you can have **new fields**, dynamically added.

if you consider adding this support, it should be structured at the begging.

**Comment by yakuter** [comment]
This is nice you to open this subject. I am not sure if we want to add lots of features which are not really used in project. I am using 1Password for a long time. It has favorites, categories etc. and all the categories has their own fields like credit cards etc.
![Screen Shot 2020-04-08 at 10 24 30](https://user-images.githubusercontent.com/3696314/78756426-73480d80-7983-11ea-82d8-e57be8909002.png)
However, I didn't use any of them. I think we must be different somehow from others. There is to way to do it.
1. You do the same job better
2. You have different features (simple or enhanced)

We can keep it simle, just search for a simple login info and auto fill with chrome extension or make something advanced.

I want to hear your ideas.

**Comment by yakuter** [comment]
I am adding a screenshot from bitwarden. Isn't it too much and complicated?
![Screen Shot 2020-04-08 at 15 20 53](https://user-images.githubusercontent.com/3696314/78783638-a5219a00-79ac-11ea-8f60-b4ea200dcc62.png)

**Comment by yakuter** [comment]
I made my decision on this subject. I started this project to have the simpliest password manager ever. So there won't be so much features. The design is as in the picture.
![Screen Shot 2020-04-11 at 12 03 38](https://user-images.githubusercontent.com/3696314/79039858-dee0e380-7bec-11ea-92a0-baf98791b7fd.png)

**Comment by ionutale** [comment]
hmmm, do we now also save credit cards?
