### ISSUE TITLE
Postgresql and login.Password type

### ISSUE THREAD

**Issue by murat** [yakuter/gpass#5]
`login.Password` is a `string` in the struct, but[ `encrypt` func generating the binary data](https://github.com/yakuter/gpass/blob/master/controller/helper/helper-controller.go#L88) for store in the `login.Password`, if you use postgresql (maybe mysql too) it throwing the `invalid byte sequence error` ([here](https://github.com/yakuter/gpass/blob/master/controller/login/create-controller.go#L27))

I think login model needs to gorm column type tags, postgresql uses `bytea` type for that.

**Comment by TheYkk** [comment]
I am working on this issue

**Comment by yakuter** [comment]
@murat thank you for your feedback. @TheYkk thanks for working on this. I assigned you with this.

**Comment by TheYkk** [comment]
Fixed : #7

**Comment by yakuter** [comment]
I tested this. Works great. Thanks a lot
