### ISSUE TITLE
Import needs to be tested manually

### ISSUE THREAD

**Issue by yakuter** [yakuter/gpass#8]
I just finished import ability. I tested it locally and it works fine. However some other tests should be great.

Also I am not sure if I explained well how to import in readme. Can you anyone check it out?

![gpass import](https://www.yakuter.com/wp-content/yuklemeler/gpass-import.png "Import Form and Request Example")

**Comment by furkanbegen** [comment]
I tested both locally and within docker but I'm getting an error like below

My Specs for local test
OS: MacOs Catalina
Go Version: 1.14

![gpass-import-error](https://user-images.githubusercontent.com/6476136/78621664-cf2f6b00-788b-11ea-969b-824d1cff707f.png)

Example csv 
`url,username,password,extra,name,grouping,fav`
`http://www.dummy.net/,dummyUname,dummyPass,,dummy.net,,0`
`https://dummy.com.tr/Login,anotherDumyUname,anotherDumyyPass,dummy.com.tr,,0`

**Comment by yakuter** [comment]
I now fixed import problems. Can you test it now. By the way, according to your dummy csv file, the form values should be like this:

URL:url
Username:username
Password:password

**Comment by furkanbegen** [comment]
I tested again and it works fine.

**Comment by safakkizkin** [comment]
I tested (two times) with same .csv file. It creates same object two times, in my opinion there should be a control. 
![image](https://user-images.githubusercontent.com/22755582/78711525-c5574780-791f-11ea-9dda-00795626cade.png)

**Comment by furkanbegen** [comment]
@safakkizkin you can multiple accounts for same website(login) so behavior is correct in my opinion

**Comment by safakkizkin** [comment]
@furkanbegen you are right about the multiple accounts. But what i want to say is, for same username and same URL, no need to create a new entry, changing the present one may the better.

**Comment by yakuter** [comment]
Well thanks for testing.

About multiple accounts, we must be flexible. However I think we shoul at least  check for if url, username and password is same at the same time. @safakkizkin It would be nice if you can handle this.

**Comment by safakkizkin** [comment]
Okay then, I will arrange a solution as you said @yakuter.

**Comment by yakuter** [comment]
Now there is same record control thanks to @safakkizkin

**Comment by ionutale** [comment]
Hi,
i think the control for duplicate entries should be made at database level using an index.

**Comment by yakuter** [comment]
Hi, when I first saw the code, I thought the same. I even tried to refactor. However our encryption method keeps password different. As you see in the pictures, the same passwords have different hashes in database.
<img width="459" alt="Screen Shot 2020-04-08 at 09 54 36" src="https://user-images.githubusercontent.com/3696314/78755814-78f12380-7982-11ea-9079-fedf0a96d5f0.png">
![Screen Shot 2020-04-08 at 09 55 58](https://user-images.githubusercontent.com/3696314/78755834-81e1f500-7982-11ea-9d35-b845178cd784.png)

Do you know any method which can solve this problem in database layer? 

By the way, I also think that we need a good password matching algorithm For example, on 1Password, if you use a password which is already used on another login, it alerts you that you used this password before, it is not unique.
