### ISSUE TITLE
Postman requests files for import

### ISSUE THREAD

**Issue by TheYkk** [yakuter/gpass#9]
Can you share Postman requests files for import local development?

**Comment by yakuter** [comment]
There is this link at README:

https://documenter.getpostman.com/view/3658426/SzYbyHXj?version=latest

I think you can grap it from there.

**Comment by TheYkk** [comment]
I can't import my postman

**Comment by yakuter** [comment]
Here you are:

https://www.yakuter.com/wp-content/yuklemeler/gpass_postman_collection.json_.zip

I also added this link to README

**Comment by TheYkk** [comment]
Thank you
